"""dd user_score and critic_score to lbum

Revision ID: 1f468ffe0efe
Revises: 8bafeab0b431
Create Date: 2025-04-30 18:04:45.237407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f468ffe0efe'
down_revision: Union[str, None] = '8bafeab0b431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('albums')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('album_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('artist_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('cover_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('genre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='albums_pkey')
    )
    # ### end Alembic commands ###
